// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMopxFEXwQfnH9gtmtLhXcAAuGfLR0-vc',
    appId: '1:332324205841:web:f8444f879da272bd6748b0',
    messagingSenderId: '332324205841',
    projectId: 'movie-app-8993e',
    authDomain: 'movie-app-8993e.firebaseapp.com',
    storageBucket: 'movie-app-8993e.appspot.com',
    measurementId: 'G-EQH4T2KG18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6D_bdvCw84n0xup2vsqU4UjRiQM_OM04',
    appId: '1:332324205841:android:762934bf6e802e736748b0',
    messagingSenderId: '332324205841',
    projectId: 'movie-app-8993e',
    storageBucket: 'movie-app-8993e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC3XKKfPDpIF8D5WdOxDaI4G0Y4kLboCI',
    appId: '1:332324205841:ios:c635ed506eca66f96748b0',
    messagingSenderId: '332324205841',
    projectId: 'movie-app-8993e',
    storageBucket: 'movie-app-8993e.appspot.com',
    iosClientId:
        '332324205841-eugsj7spsdkfr9a5dsbs4h0v1pidqgks.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC3XKKfPDpIF8D5WdOxDaI4G0Y4kLboCI',
    appId: '1:332324205841:ios:e8096cf0d6d9729b6748b0',
    messagingSenderId: '332324205841',
    projectId: 'movie-app-8993e',
    storageBucket: 'movie-app-8993e.appspot.com',
    iosClientId:
        '332324205841-2j1aebc1df043gvihne3prkbu59kktau.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp.RunnerTests',
  );
}
